wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/102_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 102_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/1618.gwas.imputed_v3.both_sexes.tsv.bgz -O 1618.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/20002_1065.gwas.imputed_v3.both_sexes.tsv.bgz -O 20002_1065.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/20002_1074.gwas.imputed_v3.both_sexes.tsv.bgz -O 20002_1074.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/20002_1111.gwas.imputed_v3.both_sexes.tsv.bgz -O 20002_1111.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/20002_1220.gwas.imputed_v3.both_sexes.tsv.bgz -O 20002_1220.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/20002_1226.gwas.imputed_v3.both_sexes.tsv.bgz -O 20002_1226.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/20003_1140884600.gwas.imputed_v3.both_sexes.tsv.bgz -O 20003_1140884600.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/20003_1141191044.gwas.imputed_v3.both_sexes.tsv.bgz -O 20003_1141191044.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/20015_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 20015_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/20016_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 20016_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/20116_0.gwas.imputed_v3.both_sexes.tsv.bgz -O 20116_0.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/20116_2.gwas.imputed_v3.both_sexes.tsv.bgz -O 20116_2.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/20150_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 20150_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/20151_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 20151_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/20153_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 20153_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/20154_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 20154_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/20548_1.gwas.imputed_v3.both_sexes.tsv.bgz -O 20548_1.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/21001_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 21001_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/21002_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 21002_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/2139_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 2139_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/22126.gwas.imputed_v3.both_sexes.tsv.bgz -O 22126.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/22506_114.gwas.imputed_v3.both_sexes.tsv.bgz -O 22506_114.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23098_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23098_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23099_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23099_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23100_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23100_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23101_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23101_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23102_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23102_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23104_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23104_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23105_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23105_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23106_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23106_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23107_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23107_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23108_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23108_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23109_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23109_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23110_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23110_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23111_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23111_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23112_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23112_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23113_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23113_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23114_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23114_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23115_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23115_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23116_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23116_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23117_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23117_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23118_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23118_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23119_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23119_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23120_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23120_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23121_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23121_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23122_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23122_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23123_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23123_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23124_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23124_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23125_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23125_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23126_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23126_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23127_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23127_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23128_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23128_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23129_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23129_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23130_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 23130_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/2443.gwas.imputed_v3.both_sexes.tsv.bgz -O 2443.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/2754_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 2754_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30000_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30000_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30010_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30010_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30020_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30020_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30030_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30030_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30040_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30040_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30050_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30050_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30070_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30070_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30080_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30080_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30090_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30090_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30100_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30100_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30110_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30110_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30120_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30120_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30130_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30130_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30140_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30140_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30180_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30180_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30190_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30190_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30200_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30200_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30210_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30210_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30240_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30240_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30250_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30250_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30260_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30260_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30270_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30270_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30280_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30280_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30290_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30290_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30300_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30300_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/3062_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 3062_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/3063_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 3063_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/3143_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 3143_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/3144_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 3144_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/3147_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 3147_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/3148_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 3148_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/3606.gwas.imputed_v3.both_sexes.tsv.bgz -O 3606.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/4080_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 4080_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/4100_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 4100_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/4101_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 4101_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/4104_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 4104_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/4105_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 4105_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/4106_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 4106_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/4119_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 4119_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/4120_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 4120_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/4123_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 4123_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/4124_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 4124_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/4125_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 4125_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/48_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 48_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/49_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 49_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/4957.gwas.imputed_v3.both_sexes.tsv.bgz -O 4957.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/4968.gwas.imputed_v3.both_sexes.tsv.bgz -O 4968.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/4990.gwas.imputed_v3.both_sexes.tsv.bgz -O 4990.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/5012.gwas.imputed_v3.both_sexes.tsv.bgz -O 5012.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/5084_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 5084_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/5085_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 5085_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/5096_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 5096_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/5097_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 5097_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/5098_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 5098_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/5099_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 5099_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/5132_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 5132_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/5133_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 5133_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/5134_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 5134_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/5135_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 5135_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/5254_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 5254_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/5255_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 5255_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/5256_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 5256_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/5257_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 5257_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/5262_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 5262_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/5263_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 5263_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/5264_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 5264_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/5265_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 5265_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/5556.gwas.imputed_v3.both_sexes.tsv.bgz -O 5556.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/6138_1.gwas.imputed_v3.both_sexes.tsv.bgz -O 6138_1.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/6138_100.gwas.imputed_v3.both_sexes.tsv.bgz -O 6138_100.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/6138_2.gwas.imputed_v3.both_sexes.tsv.bgz -O 6138_2.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/6150_100.gwas.imputed_v3.both_sexes.tsv.bgz -O 6150_100.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/6150_2.gwas.imputed_v3.both_sexes.tsv.bgz -O 6150_2.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/6150_4.gwas.imputed_v3.both_sexes.tsv.bgz -O 6150_4.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/6152_8.gwas.imputed_v3.both_sexes.tsv.bgz -O 6152_8.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/6152_9.gwas.imputed_v3.both_sexes.tsv.bgz -O 6152_9.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/680_3.gwas.imputed_v3.both_sexes.tsv.bgz -O 680_3.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/78_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 78_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/C3_OTHER_SKIN.gwas.imputed_v3.both_sexes.tsv.bgz -O C3_OTHER_SKIN.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/C3_SKIN.gwas.imputed_v3.both_sexes.tsv.bgz -O C3_SKIN.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/G56.gwas.imputed_v3.both_sexes.tsv.bgz -O G56.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/G6_CARPTU.gwas.imputed_v3.both_sexes.tsv.bgz -O G6_CARPTU.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/I25.gwas.imputed_v3.both_sexes.tsv.bgz -O I25.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/I83.gwas.imputed_v3.both_sexes.tsv.bgz -O I83.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/I9_CORATHER.gwas.imputed_v3.both_sexes.tsv.bgz -O I9_CORATHER.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/I9_DISVEINLYMPH.gwas.imputed_v3.both_sexes.tsv.bgz -O I9_DISVEINLYMPH.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/I9_IHD.gwas.imputed_v3.both_sexes.tsv.bgz -O I9_IHD.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/M16.gwas.imputed_v3.both_sexes.tsv.bgz -O M16.gwas.imputed_v3.both_sexes.tsv.bgz
